application: tcc-ciro
version: php
runtime: php55
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  script: main.php
  
- url: /sign
  script: sign.php

- url: /img
  script: img.php
